"use client";

import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api/client";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { BrainCircuit, TrendingUp, AlertTriangle, Lightbulb, Clock, CheckCircle2, XCircle } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { format } from "date-fns";

export default function AIInsightsPage() {
  const [insights, setInsights] = useState<any[]>([]);
  const [procrastination, setProcrastination] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      const [insightsRes, procRes] = await Promise.all([
        apiClient.get("/insights/generate"),
        apiClient.get("/ai/procrastination")
      ]);
      setInsights(insightsRes.data);
      setProcrastination(procRes.data);
    } catch (e) {
      toast.error("Failed to load AI Insights");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { 
    fetchInsights();
  }, []);
  
  if (loading) {
    return (
      <div className="p-4 md:p-8 space-y-6 max-w-7xl mx-auto flex items-center justify-center min-h-[50vh]">
        <div className="flex flex-col items-center gap-4 text-muted-foreground animate-pulse">
          <BrainCircuit className="h-12 w-12 text-primary" />
          <p>Gemini is analyzing your data...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 space-y-6 max-w-7xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Insights</h1>
        <p className="text-muted-foreground">Personalized intelligence generated by Gemini 2.0</p>
      </div>
      
      {procrastination && (
        <Card className={`border overflow-hidden ${
          procrastination.severity === 'high' ? 'border-destructive/50 bg-destructive/5' : 
          procrastination.severity === 'medium' ? 'border-orange-500/50 bg-orange-500/5' : 
          'border-green-500/50 bg-green-500/5'
        }`}>
          <CardHeader className="pb-4">
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2 text-xl">
                <BrainCircuit className={
                  procrastination.severity === 'high' ? 'text-destructive' : 
                  procrastination.severity === 'medium' ? 'text-orange-500' : 'text-green-500'
                }/> 
                Procrastination Analysis
              </CardTitle>
              <div className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${
                procrastination.severity === 'high' ? 'bg-destructive/20 text-destructive' : 
                procrastination.severity === 'medium' ? 'bg-orange-500/20 text-orange-500' : 
                'bg-green-500/20 text-green-500'
              }`}>
                {procrastination.severity} risk
              </div>
            </div>
            <CardDescription>Based on your activity over the last {procrastination.analysis_period_days} days</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-background rounded-lg p-3 border">
                <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><XCircle className="h-3 w-3" /> Missed Deadlines</p>
                <p className="text-2xl font-bold">{procrastination.metrics.missed_deadlines}</p>
              </div>
              <div className="bg-background rounded-lg p-3 border">
                <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><AlertTriangle className="h-3 w-3" /> Cancelled Events</p>
                <p className="text-2xl font-bold">{procrastination.metrics.cancelled_events}</p>
              </div>
              <div className="bg-background rounded-lg p-3 border">
                <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><Clock className="h-3 w-3" /> Missed Tasks</p>
                <p className="text-2xl font-bold">{procrastination.metrics.missed_tasks}</p>
              </div>
              <div className="bg-background rounded-lg p-3 border">
                <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><CheckCircle2 className="h-3 w-3" /> Completed Tasks</p>
                <p className="text-2xl font-bold">{procrastination.metrics.completed_tasks}</p>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex justify-between text-sm font-medium">
                <span>Procrastination Score</span>
                <span>{procrastination.procrastination_score} / 100</span>
              </div>
              <Progress value={procrastination.procrastination_score} className={`h-2 ${
                procrastination.severity === 'high' ? '[&>div]:bg-destructive' : 
                procrastination.severity === 'medium' ? '[&>div]:bg-orange-500' : 
                '[&>div]:bg-green-500'
              }`} />
            </div>

            <div className="bg-background rounded-xl p-4 border border-primary/20 shadow-sm relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-primary" />
              <div className="flex gap-3">
                <Lightbulb className="h-5 w-5 text-primary shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium mb-1">AI Coach Insight</p>
                  <p className="text-sm text-muted-foreground leading-relaxed">{procrastination.insight}</p>
                </div>
              </div>
            </div>

          </CardContent>
        </Card>
      )}

      <div>
        <h2 className="text-xl font-semibold tracking-tight mb-4 flex items-center gap-2">
          <TrendingUp className="h-5 w-5 text-primary" />
          General Recommendations
        </h2>
        {insights.length === 0 ? (
          <div className="p-8 text-center border rounded-xl bg-card text-muted-foreground">
            No recommendations generated yet. Try adding more events or expenses!
          </div>
        ) : (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {insights.map((insight: any, i: number) => {
              const dateIso = insight.created_at || new Date().toISOString();
              return (
                <Card key={i} className="hover:border-primary/50 transition-colors bg-gradient-to-br from-card to-card/50">
                  <CardHeader className="pb-2">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold px-2 py-1 rounded bg-primary/10 text-primary uppercase tracking-wider">
                        {insight.category}
                      </div>
                    </div>
                    <CardTitle className="text-lg mt-2 leading-tight">Insight #{i + 1}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-4 leading-relaxed">{insight.message}</p>
                    <p className="text-[10px] text-muted-foreground font-medium text-right uppercase tracking-wider">
                      Generated: {format(new Date(dateIso), "MMM d, HH:mm")}
                    </p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
